service: parameter-store-replication

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  iam:
    role:
      - Effect: "Allow"
        Action:
          # Most sync actions will happen here.
          - "ssm:GetParameters"
          - "ssm:GetParameter"
          - "ssm:PutParameter"

          # Need delete in case the source param is removed, so I can remove from target.
          - "ssm:DeleteParameter"
          - "ssm:DeleteParameters"

          # Enable secrets config retrieval (not value) and replication changes.
          - "secretsmanager:ReplicateSecretToRegions"
          -
        Resource: "*"

functions:
  handle:
    environment:
      SNS_TOPIC: "" #todo - create a topic in our mgmt account and grant access to ALL our owned accounts. Put ARN here.
      SNS_REGION: "" #todo - get region from the above topic.
      SOURCE_REGION: ${opt:source_region, 'us-west-2'}
      TARGET_REGION: ${opt:target_region, 'us-east-2'}
      ACCOUNT_ID: ${AWS::AccountId}
    handler: handler.handle
    events:
      - cloudwatchEvent:
          event:
            source:
              - "aws.ssm"
            detail-type:
              - "Parameter Store Change"