service: parameter-store-replication

frameworkVersion: '3'

provider:
  name: aws
  region: us-east-2
  runtime: python3.9
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Resource: '*'
          Action:
          # Parameter Store - Read & Sync Actions

          - "ssm:GetParameters"
          - "ssm:GetParameter"
          - "ssm:PutParameter"
          - "ssm:DeleteParameter"
          - "ssm:DeleteParameters"

          # Secrets Manager - Check & Enable Replication Configuration

          - "secretsmanager:ReplicateSecretToRegions"
          - "secretsmanager:DescribeSecret"
          - "secretsmanager:ListSecrets"

functions:
  handle:
    environment:
      SNS_TOPIC: "arn:aws:sns:us-east-2:022017851643:DemoNotificationTopic"
      SNS_REGION: "us-east-2"
      SOURCE_REGION: ${opt:source_region, 'us-east-2'}
      TARGET_REGION: ${opt:target_region, 'us-east-1'}
      ACCOUNT_ID: ${AWS::AccountId}
    handler: handler.handle
#    events:
#      # 9-10 AM Eastern Every Day (DST variance) - sync everything to catch missed items.
#      - schedule:
#          rate:  cron(0 14 * * ? *)
#          input:
#            detail:
#              name: "all"
#              operation: "sync"
#
#      # The following triggers are subject to a variable delay due to reliance on CloudTrail logs:
#
#      # Any change to a parameter triggers immediate sync.
#      - cloudwatchEvent:
#          event:
#            source:
#              - "aws.ssm"
#            detail-type:
#              - "Parameter Store Change"
#
#      # A newly created Secret gets replication config.
#      - cloudwatchEvent:
#          event:
#            source:
#              - "aws.secretsmanager"
#            detail-type:
#              - "AWS API Call via CloudTrail"
#            detail:
#              eventName:
#                - CreateSecret