service: parameter-store-replication

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  iam:
    role:
      - Effect: "Allow"
        Action:
          # Most sync actions will happen here.
          - "ssm:GetParameters"
          - "ssm:GetParameter"
          - "ssm:PutParameter"

          # Need delete in case the source param is removed, so I can remove from target.
          - "ssm:DeleteParameter"
          - "ssm:DeleteParameters"
        Resource: "*"

functions:
  replicate:
    environment:
      source_region: ${opt:source_region, 'us-west-2'}
      target_region: ${opt:target_region, 'us-east-2'}
    handler: handler.replicate
    events:
      - cloudwatchEvent:
          event:
            source:
              - "aws.ssm"
            detail-type:
              - "Parameter Store Change"