service: parameter-store-replication

frameworkVersion: '3'

provider:
  name: aws
  region: us-east-2
  runtime: python3.9
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Resource: '*'
          Action:
          # Parameter Store - Read & Sync Actions

          - "ssm:GetParameters"
          - "ssm:GetParameter"
          - "ssm:PutParameter"
          - "ssm:DeleteParameter"
          - "ssm:DeleteParameters"

          # Secrets Manager - Check & Enable Replication Configuration

          - "secretsmanager:ReplicateSecretToRegions"
          - "secretsmanager:DescribeSecret"
          - "secretsmanager:ListSecrets"

functions:
  handle:
    environment:
      SNS_TOPIC: "" #todo - create a topic in our mgmt account and grant access to ALL our owned accounts. Put ARN here.
      SNS_REGION: "" #todo - get region from the above topic.
      SOURCE_REGION: ${opt:source_region, 'us-east-2'}
      TARGET_REGION: ${opt:target_region, 'us-east-1'}
      ACCOUNT_ID: ${AWS::AccountId}
    handler: handler.handle
    events:
      - cloudwatchEvent:
          event:
            source:
              - "aws.ssm"
            detail-type:
              - "Parameter Store Change"